### ISSUE TITLE
generate bindings on the fly

### ISSUE THREAD

**Issue by igor-raits** [BurntSushi/rust-pcre2#1]
it would be cool if you would generate bindings using bindgen from build.rs.

Thanks!

**Comment by BurntSushi** [comment]
Unless I'm missing something, this creates a build time dependency on having bindgen installed. I am most definitely not okay with that. Could you perhaps say more about why you want this?

**Comment by BurntSushi** [comment]
We talked about this briefly on IRC, and my understanding is that this is desirable so that users who compile `pcre2-sys` automatically get any benefits that bindgen may have acquired. I agree that is a nice benefit, but I also think it is a very minor benefit, and that it's not too much trouble to just updated `pcre2-sys` with a re-run of `bindgen` to get updates. I wouldn't really expect this to matter too much in practice anyway.

In particular, I do not think it is worth requiring bindgen to be installed in order to build `pcre2-sys`. I honestly kind of see that as a fairly onerous requirement compared to what you need today: Cargo and a C compiler.

If it's possible for us to *optionally* use bindgen, then I might be open to that, but I still kind of think it's probably more effort than it's worth.

I'm happy to re-open this, but I think it's probably more accurate to just close this for now. Thanks!
