### ISSUE TITLE
jit4lyfe fails on s390x

### ISSUE THREAD

**Issue by igor-raits** [BurntSushi/rust-pcre2#3]
```rust
---- bytes::tests::jit4lyfe stdout ----
thread 'bytes::tests::jit4lyfe' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: JIT, code: -45, offset: None, message: "bad JIT option" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by BurntSushi** [comment]
I don't think I even know what `s390x` is. Does Travis CI support that platform?

Basically, the test that's failing is a test that tries to execute a PCRE2 match function using it's JIT. I guess JIT support probably isn't available on all platforms. I can `cfg` this test to only run on `x86_64`, but that's just kicking the can down the road. I think we'll need to provide a way to query whether the JIT is enabled or not so that tools like ripgrep can use it.

I'll try to get this fixed soon, although I don't know how to test s390x...

**Comment by BurntSushi** [comment]
Interestingly, [PCRE2's JIT docs](https://www.pcre.org/current/doc/html/pcre2jit.html) say this:

> A program can tell if JIT support is available by calling pcre2_config() with the PCRE2_CONFIG_JIT option. The result is 1 when JIT is available, and 0 otherwise. However, a simple program does not need to check this in order to use JIT. The API is implemented in a way that falls back to the interpretive code if JIT is not available.

So in theory this shouldn't happen? But the docs go on to say:

> If JIT support is not available, a call to pcre2_jit_compile() does nothing and returns PCRE2_ERROR_JIT_BADOPTION. Otherwise, the compiled pattern is passed to the JIT compiler, which turns it into machine code that executes much faster than the normal interpretive code, but yields exactly the same results. The returned value from pcre2_jit_compile() is zero on success, or a negative error code.

Which is what appears to be happening here.

**Comment by igor-raits** [comment]
> s390x

https://fedoraproject.org/wiki/Architectures/s390x

I can test anything what you would like on that machine.

**Comment by BurntSushi** [comment]
@ignatenkobrain If I submit a PR can you test that before I merge it? If so that would be great! I'll work on this now.

**Comment by igor-raits** [comment]
@BurntSushi yup, just give me a link ;)
